global:
  message: welcome to order service!
  
server:
  port: 8083
  message: Hello from prod environment!

spring:
  application:
    name: order-service  
    
  datasource:
    url: jdbc:mysql://mysql-order:3306/orderdb_prod
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka/

logging:
  level:
    org.springframework.web: INFO

management:
  endpoints:
    web:
      exposure:
        include: "*"
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000

resilience4j:
  circuitbreaker:
    instances:
      customerServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
      productServiceCB:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

